eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    name: localhost

spring:
  application:
    name: CLOUD-GATEWAY
  cloud:
    gateway:
      routes:
        - id: ORDER-API
          uri: lb://ORDER-API
          predicates:
            - Path=/order/**
        - id: PAYMENT-API
          uri: lb://PAYMENT-API
          predicates:
            - Path=/payment/**
        - id: PRODUCT-API
          uri: lb://PRODUCT-API
          predicates:
            - Path=/product/**
  main:
    web-application-type: reactive

server:
  port: 9090


